// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riidfqrkldnelqwkeszq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpaWRmcXJrbGRuZWxxd2tlc3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NjQwNjgsImV4cCI6MjA1MDM0MDA2OH0.0oc9tRcfKWmn2Wy-J_SurusPeA_d2FzifUQKiA61f08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);